version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: faker
    versions:
    - 5.2.0
    - 5.3.1
    - 5.4.0
    - 5.5.0
    - 5.5.1
    - 5.5.2
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: pg
    versions:
    - 8.5.1
